name: flutube
description: Youtube video downloader made using flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  equatable: ^2.0.3
  file_picker: ^4.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_staggered_grid_view: ^0.4.0
  hooks_riverpod: ^1.0.0-dev.7
  intl: ^0.17.0
  ionicons: ^0.1.2
  material_floating_search_bar: ^0.3.4
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  readmore: ^2.1.0
  salomon_bottom_bar: ^3.1.0
  share_plus: ^2.1.4
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  timeago: ^3.1.0
  youtube_explode_dart: ^1.10.5+1

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
