name: flutube
description: Youtube client made using flutter.

publish_to: none
version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adwaita: ^0.5.1
  ant_icons: ^2.0.0-nullsafety.0
  bitsdojo_window: ^0.1.1+1
  bot_toast: ^4.0.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.0
  custom_text: ^0.6.0-dev.1
  # dart_vlc: ^0.1.7
  dio: ^4.0.4
  equatable: ^2.0.3
  file_picker: ^4.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.0-dev.0
  intl: ^0.17.0
  libadwaita:
    git:
      url: https://github.com/gtk-flutter/libadwaita.git
      ref: fix46
  open_file: # Upgrade to pub.dev when package > 3.2.1
    git:
      url: https://github.com/miDeb/open_file.git
      ref: no_system
  package_info_plus: ^1.3.0
  page_transition: ^2.0.5
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  piped_api:
    git:
      url: https://github.com/TeamPiped/piped_dart
  readmore: ^2.1.0
  share_plus: ^3.0.4
  shared_preferences: ^2.0.13
  sticky_headers: ^0.2.0
  timeago: ^3.2.1
  url_launcher: ^6.0.18
  youtube_explode_dart: 
    git:
      url: https://github.com/Hexer10/youtube_explode_dart.git
  youtube_player_iframe: ^2.2.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.1
  very_good_analysis: ^2.4.0

dependency_overrides:
  nm: ^0.5.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700
